
title: Nashwan's Homepage
page-top-title: Nashwan Mustafa
top-section-bg-text: Kubernetes and Cloud Platform Engineer
# home-subtitle: Nashwan Mustafa&ensp;|&ensp;Neşwan Mustefa
home-subtitle: Some Thoughts Of Platform Engineering&ensp;|&ensp;Hin Ramanên Endezyariya Platforma Teknolojiyê
copyright-text: '&copy; Nashwan 2024. All Rights Reserved.'
